### ISSUE TITLE
GitHub Actions builds/releases

### ISSUE THREAD

**Issue by jerr0328** [wolfg1969/drf-dash#6]
Thanks for providing a docset for DRF! I'd like to get newer versions built, as the latest DRF is 3.14.0 but the newest docset is only 3.11.0. Would it make sense to have a GitHub action that can build new versions of DRF more (semi)automatically and publish the .tgz file as an artifact? There are also some docsets that use some automation to push update PRs: https://github.com/roberth-k/dash-docset-aws-cdk, though DRF doesn't release that often so it might be overkill 😆 Let me know also if you're looking for any help maintaining this

**Comment by wolfg1969** [comment]
@jerr0328 I've setup GitHub Action on this repo. Version 3.14.0 was created and PR is waiting to be merged.

**Comment by wolfg1969** [comment]
@jerr0328 Version 3.14.0 was merged.
